<?php
// Array de provincias por departamento
function obtener_provincias($departamento) {
    $provincias = array(
        'Amazonas' => array('Bagua', 'Bongará', 'Chachapoyas', 'Condorcanqui', 'Luya', 'Rodríguez de Mendoza', 'Utcubamba'),
        'Áncash' => array('Aija', 'Antonio Raymondi', 'Asunción', 'Bolognesi', 'Carhuaz', 'Carlos Fermín Fitzcarrald', 'Casma', 'Corongo', 'Huaraz', 'Huari', 'Huarmey', 'Huaylas', 'Mariscal Luzuriaga', 'Ocros', 'Pallasca', 'Pomabamba', 'Recuay', 'Santa', 'Sihuas', 'Yungay'),
        'Apurímac' => array('Abancay', 'Andahuaylas', 'Antabamba', 'Aymaraes', 'Chincheros', 'Cotabambas', 'Grau'),
        'Arequipa' => array('Arequipa', 'Camaná', 'Caravelí', 'Castilla', 'Caylloma', 'Condesuyos', 'Islay', 'La Unión'),
        'Ayacucho' => array('Cangallo', 'Huamanga', 'Huanca Sancos', 'Huanta', 'La Mar', 'Lucanas', 'Parinacochas', 'Páucar del Sara Sara', 'Sucre', 'Víctor Fajardo', 'Vilcas Huamán'),
        'Cajamarca' => array('Cajabamba', 'Cajamarca', 'Celendín', 'Chota', 'Contumazá', 'Cutervo', 'Hualgayoc', 'Jaén', 'San Ignacio', 'San Marcos', 'San Miguel', 'San Pablo', 'Santa Cruz'),
        'Callao' => array('Callao'),
        'Cusco' => array('Acomayo', 'Anta', 'Calca', 'Canas', 'Canchis', 'Chumbivilcas', 'Cusco', 'Espinar', 'La Convención', 'Paruro', 'Paucartambo', 'Quispicanchi', 'Urubamba'),
        'Huancavelica' => array('Acobamba', 'Angaraes', 'Castrovirreyna', 'Churcampa', 'Huancavelica', 'Huaytará', 'Tayacaja'),
        'Huánuco' => array('Ambo', 'Dos de Mayo', 'Huacaybamba', 'Huamalíes', 'Huánuco', 'Lauricocha', 'Leoncio Prado', 'Marañón', 'Pachitea', 'Puerto Inca', 'Yarowilca'),
        'Ica' => array('Chincha', 'Ica', 'Nazca', 'Palpa', 'Pisco'),
        'Junín' => array('Chanchamayo', 'Chupaca', 'Concepción', 'Huancayo', 'Jauja', 'Junín', 'Satipo', 'Tarma', 'Yauli'),
        'La Libertad' => array('Ascope', 'Bolívar', 'Chepén', 'Gran Chimú', 'Julcán', 'Otuzco', 'Pacasmayo', 'Pataz', 'Sánchez Carrión', 'Santiago de Chuco', 'Trujillo', 'Virú'),
        'Lambayeque' => array('Chiclayo', 'Ferreñafe', 'Lambayeque'),
        'Lima' => array('Barranca', 'Cajatambo', 'Canta', 'Cañete', 'Huaral', 'Huarochirí', 'Huaura', 'Oyón', 'Yauyos'),
        'Loreto' => array('Alto Amazonas', 'Datem del Marañón', 'Loreto', 'Mariscal Ramón Castilla', 'Maynas', 'Putumayo', 'Requena', 'Ucayali'),
        'Madre de Dios' => array('Manu', 'Tahuamanu', 'Tambopata'),
        'Moquegua' => array('General Sánchez Cerro', 'Ilo', 'Mariscal Nieto'),
        'Pasco' => array('Daniel Alcides Carrión', 'Oxapampa', 'Pasco'),
        'Piura' => array('Ayabaca', 'Huancabamba', 'Morropón', 'Paita', 'Piura', 'Sechura', 'Sullana', 'Talara'),
        'Puno' => array('Azángaro', 'Carabaya', 'Chucuito', 'El Collao', 'Huancané', 'Lampa', 'Melgar', 'Moho', 'Puno', 'San Antonio de Putina', 'San Román', 'Sandia', 'Yunguyo'),
        'San Martín' => array('Bellavista', 'El Dorado', 'Huallaga', 'Lamas', 'Mariscal Cáceres', 'Moyobamba', 'Picota', 'Rioja', 'San Martín', 'Tocache'),
        'Tacna' => array('Candarave', 'Jorge Basadre', 'Tacna', 'Tarata'),
        'Tumbes' => array('Contralmirante Villar', 'Tumbes', 'Zarumilla'),
        'Ucayali' => array('Atalaya', 'Coronel Portillo', 'Padre Abad', 'Purús'),

        // Agrega los demás departamentos y provincias
    );

    return isset($provincias[$departamento]) ? $provincias[$departamento] : array();
}

function obtener_distritos($provincia) {
    $distritos = array(
        'Bagua' => array('Aramango', 'Bagua', 'Copallín', 'El Parco', 'Imaza', 'La Peca'),
        'Bongará' => array('Chisquilla', 'Churuja', 'Corosha', 'Cuispes', 'Florida', 'Jumbilla', 'Recta', 'San Carlos', 'Shipasbamba', 'Valera', 'Yambrasbamba'),
        'Chachapoyas' => array('Asunción', 'Balsas', 'Chachapoyas', 'Cheto', 'Chiliquín', 'Chuquibamba', 'Granada', 'Huancas', 'La Jalca', 'Leimebamba', 'Levanto', 'Magdalena', 'Mariscal Castilla', 'Molino Pampa', 'Montevideo', 'Olleros', 'Quinjalca', 'San Francisco de Daguas', 'San Isidro de Maino', 'Soloco', 'Sonche'),
        'Condorcanqui' => array('El Cenepa', 'Nieva', 'Río Santiago'),
        'Luya' => array('Camporredondo', 'Cocabamba', 'Colcamar', 'Conila', 'Inguilpata', 'Lamud', 'Longuita', 'Lonya Chico', 'Luya', 'Luya Viejo', 'María', 'Ocalli', 'Ocumal', 'Pisuquia', 'Providencia', 'San Cristóbal', 'San Francisco del Yeso', 'San Jerónimo', 'San Juan de Lopecancha', 'Santa Catalina', 'Santo Tomás', 'Tingo', 'Trita'),
        'Rodríguez de Mendoza' => array('Chirimoto', 'Cochamal', 'Huambo', 'Limabamba', 'Longar', 'Mariscal Benavides', 'Milpuc', 'Omia', 'Santa Rosa', 'Totora', 'Vista Alegre'),
        'Utcubamba' => array('Bagua Grande', 'Cajaruro', 'Cumba', 'El Milagro', 'Jamalca', 'Lonya Grande', 'Yamón'),
        'Aija' => array('Aija', 'Coris', 'Huacllán', 'La Merced', 'Succha'),
        'Antonio Raymondi' => array('Aczo', 'Chaccho', 'Chingas', 'Llamellín', 'Mirgas', 'San Juan de Rontoy'),
        'Asunción' => array('Chacas', 'Acochaca'),
        'Bolognesi' => array('Abelardo Pardo Lezameta', 'Antonio Raymondi', 'Aquia', 'Cajacay', 'Canis', 'Chiquián', 'Colquioc', 'Huallanca', 'Huasta', 'Huayllacayán', 'La Primavera', 'Mangas', 'Pacllón', 'San Miguel de Corpanqui', 'Ticllos'),
        'Carhuaz' => array('Acopampa', 'Amashca', 'Anta', 'Ataquero', 'Carhuaz', 'Compedrada', 'Marcará', 'Pariahuanca', 'San Miguel de Aco', 'Shilla', 'Tinco', 'Yungar'),
        'Carlos Fermín Fitzcarrald' => array('San Luis', 'San Nicolás', 'Yauya'),
        'Casma' => array('Buena Vista Alta', 'Casma', 'Comandante Noel', 'Yaután'),
        'Corongo' => array('Aco', 'Bambas', 'Corongo', 'Cusca', 'La Pampa', 'Yanac', 'Yupan'),
        'Huaraz' => array('Cochabamba', 'Colcabamba', 'Huanchay', 'Huaraz', 'Independencia', 'Jangas', 'La Libertad', 'Olleros', 'Pampas Grande', 'Pariacoto', 'Pira', 'Tarica'),
        'Huari' => array('Anra', 'Cajay', 'Chavín de Huantar', 'Huacachi', 'Huacchis', 'Huachis', 'Huantar', 'Huari', 'Masin', 'Paucas', 'Ponto', 'Rahuapampa', 'Rapayán', 'San Marcos', 'San Pedro de Chaná', 'Uco'),
        'Huarmey' => array('Cochapeti', 'Culebras', 'Huarmey', 'Malvas'),
        'Huaylas' => array('Caraz', 'Huallanca', 'Huata', 'Huaylas', 'Mato', 'Pamparomás', 'Pueblo Libre', 'Santa Cruz', 'Santo Toribio', 'Yuracmarca'),
        'Mariscal Luzuriaga' => array('Casca', 'Eleazar Guzmán Barrón', 'Fidel Olivas Escudero', 'Llama', 'Llumpa', 'Lucma', 'Musga', 'Piscobamba'),
        'Ocros' => array('Acas', 'Cajamarquilla', 'Carhuapampa', 'Cochas', 'Congas', 'Llipa', 'Ocros', 'San Cristóbal de Raján', 'San Pedro', 'Santiago de Chilcas'),
        'Pallasca' => array('Bolognesi', 'Cabana', 'Conchucos', 'Huacaschuque', 'Huandoval', 'Lacabamba', 'Llapo', 'Pallasca', 'Pampas', 'Santa Rosa', 'Tauca'),
        'Pomabamba' => array('Huayllán', 'Parobamba', 'Pomabamba', 'Quinuabamba'),
        'Recuay' => array('Catac', 'Cotaparaco', 'Huayllapampa', 'Llacllín', 'Marca', 'Pampas Chico', 'Pararín', 'Recuay', 'Tapacocha', 'Ticapampa'),
        'Santa' => array('Cáceres del Perú', 'Chimbote', 'Coishco', 'Macate', 'Moro', 'Nepeña', 'Nuevo Chimbote', 'Samanco', 'Santa'),
        'Sihuas' => array('Acobamba', 'Alfonso Ugarte', 'Cashapampa', 'Chingalpo', 'Huayllabamba', 'Quiches', 'Ragash', 'San Juan', 'Sicsibamba', 'Sihuas'),
        'Yungay' => array('Cascapara', 'Mancos', 'Matacoto', 'Quillo', 'Ranrahirca', 'Shupluy', 'Yungay'),
        'Abancay' => array('Abancay', 'Chacoche', 'Circa', 'Curahuasi', 'Huanipaca', 'Lambrama', 'Pichirhua', 'San Pedro de Cachora', 'Tamburco'),
        'Andahuaylas' => array('Andahuaylas', 'Andarapa', 'Chiara', 'Huancarama', 'Huancaray', 'Huayana', 'Kaquiabamba', 'Kishuara', 'Pacobamba', 'Pacucha', 'Pampachiri', 'Pomacocha', 'San Antonio de Cachi', 'San Jerónimo', 'San Miguel de Chaccrampa', 'Santa María de Chicmo', 'Talavera', 'Tumay Huaraca', 'Turpo'),
        'Antabamba' => array('Antabamba', 'El Oro', 'Huaquirca', 'Juan Espinoza Medrano', 'Oropesa', 'Pachaconas', 'Sabaino'),
        'Aymaraes' => array('Capaya', 'Caraybamba', 'Chalhuanca', 'Chapimarca', 'Colcabamba', 'Cotaruse', 'Huayllo', 'Justo Apu Sahuaraura', 'Lucre', 'Pocohuanca', 'San Juan de Chacña', 'Sañayca', 'Soraya', 'Tapairihua', 'Tintay', 'Toraya', 'Yanaca'),
        'Chincheros' => array('Anco-Huallo', 'Chincheros', 'Cocharcas', 'Huaccana', 'Ocobamba', 'Ongoy', 'Ranracancha', 'Uranmarca'),
        'Cotabambas' => array('Challhuahuacho', 'Cotabambas', 'Coyllurqui', 'Haquira', 'Mara', 'Tambobamba'),
        'Grau' => array('Chuquibambilla', 'Curasco', 'Curpahuasi', 'Huaillla', 'Mamara', 'Micaela Bastidas', 'Pataypampa', 'Progreso', 'San Antonio', 'Santa Rosa', 'Turpay', 'Vilcabamba', 'Virundo'),
        'Arequipa' => array('Alto Selva Alegre', 'Arequipa', 'Cayma', 'Cerro Colorado', 'Characato', 'Chiguata', 'Jacobo Hunter', 'La Joya', 'Mariano Melgar', 'Miraflores', 'Mollebaya', 'Paucarpata', 'Pocsi', 'Polobaya', 'Quequeña', 'Sabandía', 'Sachaca', 'San Juan de Siguas', 'San Juan de Tarucani', 'Santa Isabel de Siguas', 'Santa Rita de Siguas', 'Socabaya', 'Tiabaya', 'Uchumayo', 'Vítor', 'Yanahuara', 'Yarabamba', 'Yura', 'José Luis Bustamante y Rivero'),
        'Camaná' => array('Camaná', 'José María Quimper', 'Mariano Nicolás Valcárcel', 'Mariscal Cáceres', 'Nicolás de Piérola', 'Ocoña', 'Quilca', 'Samuel Pastor'),
        'Caravelí' => array('Acarí', 'Atico', 'Atiquipa', 'Bella Unión', 'Cahuacho', 'Caravelí', 'Chala', 'Cháparra', 'Huanuhuanu', 'Jaquí', 'Lomas', 'Quicacha', 'Yauca'),
        'Castilla' => array('Andagua', 'Aplao', 'Ayo', 'Chachas', 'Chilcaymarca', 'Choco', 'Huancarqui', 'Machaguay', 'Orcopampa', 'Pampacolca', 'Tipán', 'Uñón', 'Uraca', 'Viraco'),
        'Caylloma' => array('Achoma', 'Cabanaconde', 'Callalli', 'Caylloma', 'Chivay', 'Coporaque', 'Huambo', 'Huanca', 'Ichupampa', 'Lari', 'Lluta', 'Maca', 'Madrigal', 'San Antonio de Chuca', 'Sibayo', 'Tapay', 'Tisco', 'Tuti', 'Yanque'),
        'Condesuyos' => array('Andaray', 'Cayarani', 'Chichas', 'Chuquibamba', 'Iray', 'Río Grande', 'Salamanca', 'Yanaquihua'),
        'Islay' => array('Cocachacra', 'Dean Valdivia', 'Islay', 'Mejía', 'Mollendo', 'Punta de Bombón'),
        'La Unión' => array('Alca', 'Charcana', 'Cotahuasi', 'Huaynacotas', 'Pampamarca', 'Puyca', 'Quechualla', 'Sayla', 'Tauria', 'Tomepampa', 'Toro'),
        'Cangallo' => array('Cangallo', 'Chuschi', 'Los Morochucos', 'María Parado de Bellido', 'Paras', 'Totos'),
        'Huamanga' => array('Acocro', 'Acos Vinchos', 'Ayacucho', 'Carmen Alto', 'Chiara', 'Jesús Nazareno', 'Ocros', 'Pacaycasa', 'Quinua', 'San José de Ticllas', 'San Juan Bautista', 'Santiago de Pischa', 'Socos', 'Tambillo', 'Vinchos'),
        'Huanca Sancos' => array('Carapo', 'Sacsamarca', 'Sancos', 'Santiago de Lucanamarca'),
        'Huanta' => array('Ayahuanco', 'Huamanguilla', 'Huanta', 'Iguain', 'Luricocha', 'Santillana', 'Sivia', 'Llochegua', 'Canayre', 'Uchuraccay', 'Pucacolpa', 'Chaca'),
        'La Mar' => array('Anco', 'Ayna', 'Chilcas', 'Chungui', 'Luis Carranza', 'San Miguel', 'Santa Rosa', 'Tambo', 'Samugari', 'Anchihuay'),
        'Lucanas' => array('Aucara', 'Cabana', 'Carmen Salcedo', 'Chaviña', 'Chipao', 'Huac-Huas', 'Laramate', 'Leoncio Prado', 'Llauta', 'Lucanas', 'Ocaña', 'Otoca', 'Puquio', 'Saisa', 'San Cristóbal', 'San Juan', 'San Pedro', 'San Pedro de Palco', 'Sancos', 'Santa Ana de Huaycahuacho', 'Santa Lucia'),
        'Parinacochas' => array('Coracora', 'Chumpi', 'Coronel Castañeda', 'Pacapausa', 'Pullo', 'Puyusca', 'San Francisco de Ravacayco', 'Upahuacho'),
        'Páucar del Sara Sara' => array('Colloni', 'Corculla', 'Lampa', 'Marcabamba', 'Oyolo', 'Pararca', 'Pausa', 'San Javier de Alpabamba', 'San José de Ushua', 'Sara Sara'),
        'Sucre' => array('Belén', 'Chalcos', 'Chilcayoc', 'Huacaña', 'Morcolla', 'Paico', 'Querobamba', 'San Pedro de Larcay', 'San Salvador de Quije', 'Santiago de Paucaray', 'Soras'),
        'Víctor Fajardo' => array('Alcamenca', 'Apongo', 'Asquipata', 'Canaria', 'Cayara', 'Colca', 'Huamanquiquia', 'Huancapi', 'Huancaraylla', 'Huaya', 'Sarhua', 'Vilcanchos'),
        'Vilcas Huamán' => array('Accomarca', 'Carhuanca', 'Concepción', 'Huambalpa', 'Independencia', 'Saurama', 'Vilcas Huamán', 'Vischongo'),
        //Cajamarca
        'Cajabamba' => array('Cachachi', 'Cajabamba', 'Condebamba', 'Sitacocha'),
        'Cajamarca' => array('Asunción', 'Cajamarca', 'Chetilla', 'Cospán', 'Encañada', 'Jesús', 'Llacanora', 'Los Baños del Inca', 'Magdalena', 'Matara', 'Namora', 'San Juan'),
        'Celendín' => array('Celendín', 'Chumuch', 'Cortegana', 'Huasmin', 'José Gálvez', 'La Libertad de Pallán', 'Miguel Iglesias', 'Oxamarca', 'Sorochuco', 'Sucre', 'Utco'),
        'Chota' => array('Anguía', 'Chadín', 'Chalamarca', 'Chiguirip', 'Chimban', 'Choropampa', 'Chota', 'Cochabamba', 'Conchán', 'Huambos', 'Lajas', 'Llama', 'Miracosta', 'Paccha', 'Pion', 'Querocoto', 'San Juan de Licupis', 'Tacabamba', 'Tocmoche'),
        'Contumazá' => array('Chilete', 'Contumazá', 'Cupisnique', 'Guzmango', 'San Benito', 'Santa Cruz de Toledo', 'Tantarica', 'Yonan'),
        'Cutervo' => array('Callayuc', 'Choros', 'Cujillo', 'Cutervo', 'La Ramada', 'Pimpingos', 'Querocotillo', 'San Andrés de Cutervo', 'San Juan de Cutervo', 'San Luis de Lucma', 'Santa Cruz', 'Santo Domingo de la Capilla', 'Santo Tomás', 'Socota', 'Toribio Casanova'),
        'Hualgayoc' => array('Bambamarca', 'Chugur', 'Hualgayoc'),
        'Jaén' => array('Bellavista', 'Chontali', 'Colasay', 'Huabal', 'Jaén', 'Las Pirias', 'Pomahuaca', 'Pucará', 'Sallique', 'San Felipe', 'San José del Alto', 'Santa Rosa'),
        'San Ignacio' => array('Chirinos', 'Huarango', 'La Coipa', 'Namballe', 'San Ignacio', 'San José de Lourdes', 'Tabaconas'),
        'San Marcos' => array('Chancay', 'Eduardo Villanueva', 'Gregorio Pita', 'Ichocán', 'José Sabogal', 'Pedro Gálvez'),
        'San Miguel' => array('Bolívar', 'Calquis', 'Catilluc', 'El Prado', 'La Florida', 'Llapa', 'Nanchoc', 'Niepos', 'San Gregorio', 'San Miguel', 'San Silvestre de Cochan', 'Tongod', 'Unión Agua Blanca'),
        'San Pablo' => array('San Bernardino', 'San Luis', 'San Pablo', 'Tumbaden'),
        'Santa Cruz' => array('Andabamba', 'Catache', 'Chancaybaños', 'La Esperanza', 'Ninabamba', 'Pulan', 'Santa Cruz', 'Saucepampa', 'Sexi', 'Uticyacu', 'Yauyucan'),
        //Callao
        'Callao' => array('Callao', 'Bellavista', 'Carmen de La Legua Reynoso', 'La Perla', 'La Punta', 'Ventanilla', 'Mi Perú'),
        //Cusco
        'Acomayo' => array('Acomayo', 'Acopia', 'Acos', 'Mosoc Llacta', 'Pomacanchi', 'Rondocan', 'Sangarará'),
        'Anta' => array('Ancahuasi', 'Anta', 'Cachimayo', 'Chinchaypujio', 'Huarocondo', 'Limatambo', 'Mollepata', 'Pucyura', 'Zurite'),
        'Calca' => array('Coya', 'Lamay', 'Lares', 'Pisac', 'San Salvador', 'Taray', 'Yanatile', 'Calca'),
        'Canas' => array('Checca', 'Kunturkanki', 'Langui', 'Layo', 'Pampamarca', 'Quehue', 'Túpac Amaru', 'Yanaoca'),
        'Canchis' => array('Checacupe', 'Combapata', 'Marangani', 'Pitumarca', 'San Pablo', 'San Pedro', 'Sicuani', 'Tinta'),
        'Chumbivilcas' => array('Capacmarca', 'Chamaca', 'Colquemarca', 'Livitaca', 'Llusco', 'Quiñota', 'Santo Tomás', 'Velille'),
        'Cusco' => array('Ccorca', 'Cusco', 'Poroy', 'San Jerónimo', 'San Sebastián', 'Santiago', 'Saylla', 'Wanchaq'),
        'Espinar' => array('Alto Pichigua', 'Condoroma', 'Coporaque', 'Ocoruro', 'Pallpata', 'Pichigua', 'Suyckutambo', 'Yauri'),
        'La Convención' => array('Echarate', 'Huayopata', 'Inkawasi', 'Kimbiri', 'Maranura', 'Ocobamba', 'Pichari', 'Quellouno', 'Santa Ana', 'Santa Teresa', 'Vilcabamba'),
        'Paruro' => array('Accha', 'Ccapi', 'Colcha', 'Huanoquite', 'Omacha', 'Paccaritambo', 'Paruro', 'Pillpinto', 'Yaurisque'),
        'Paucartambo' => array('Caicay', 'Challabamba', 'Colquepata', 'Huancarani', 'Kosñipata', 'Paucartambo'),
        'Quispicanchi' => array('Andahuaylillas', 'Camanti', 'Ccarhuayo', 'Ccatca', 'Cusipata', 'Huaro', 'Lucre', 'Marcapata', 'Ocongate', 'Oropesa', 'Quiquijana', 'Urcos'),
        'Urubamba' => array('Chinchero', 'Huayllabamba', 'Machupicchu', 'Maras', 'Ollantaytambo', 'Urubamba', 'Yucay'),
        //Huancavelica
        'Acobamba' => array('Acobamba', 'Andabamba', 'Anta', 'Caja', 'Marcas', 'Paucara', 'Pomacocha', 'Rosario'),
        'Angaraes' => array('Anchonga', 'Callanmarca', 'Ccochaccasa', 'Chincho', 'Congalla', 'Huanca-Huanca', 'Huayllay Grande', 'Julcamarca', 'Lircay', 'San Antonio de Antaparco', 'Santo Tomás de Pata', 'Secclla'),
        'Castrovirreyna' => array('Arma', 'Aurahuá', 'Capillas', 'Castrovirreyna', 'Chupamarca', 'Cocas', 'Huachos', 'Huamatambo', 'Mollepampa', 'San Juan', 'Santa Ana', 'Tantara', 'Ticrapo'),
        'Churcampa' => array('Anco', 'Chinchihuasi', 'Churcampa', 'Cosme', 'El Carmen', 'La Merced', 'Locroja', 'Pachamarca', 'Paucarbamba', 'San Miguel de Mayocc', 'San Pedro de Coris'),
        'Huancavelica' => array('Acobambilla', 'Acoria', 'Conayca', 'Cuenca', 'Huachocolpa', 'Huancavelica', 'Huando', 'Huayllahuara', 'Izcuchaca', 'Laria', 'Manta', 'Mariscal Cáceres', 'Moya', 'Nuevo Occoro', 'Palca', 'Pilchaca', 'Vilca', 'Yauli', 'Ascensión'),
        'Huaytará' => array('Ayaví', 'Córdova', 'Huayacundo Arma', 'Huaytará', 'Laramarca', 'Ocoyo', 'Pilpichaca', 'Querco', 'Quito-Arma', 'San Antonio de Cusicancha', 'San Francisco de Sangayaico', 'San Isidro', 'Santiago de Chocorvos', 'Santiago de Quirahuara', 'Santo Domingo de Capillas', 'Tambo'),
        'Tayacaja' => array('Acostambo', 'Acraquia', 'Ahuaycha', 'Colcabamba', 'Cuenca', 'Daniel Hernández', 'Huachocolpa', 'Huaribamba', 'Ñahuimpuquio', 'Pampas', 'Pazos', 'Quishuar', 'Salcabamba', 'Salcahuasi', 'San Marcos de Rocchac', 'Surcubamba', 'Tintay Puncu'),
        //Huánuco
        'Ambo' => array('Ambo', 'Cayna', 'Colpas', 'Conchamarca', 'Huacar', 'San Francisco', 'San Rafael', 'Tomay Kichwa'),
        'Dos de Mayo' => array('Chuquis', 'La Unión', 'Marias', 'Pachas', 'Quivilla', 'Ripan', 'Shunqui', 'Sillapata', 'Yanas'),
        'Huacaybamba' => array('Canchabamba', 'Cochabamba', 'Huacaybamba', 'Pinra'),
        'Huamalíes' => array('Arancay', 'Chavín de Pariarca', 'Jacas Grande', 'Jircan', 'Llata', 'Miraflores', 'Monzón', 'Punchao', 'Puños', 'Singa', 'Tantamayo'),
        'Huánuco' => array('Amarilis', 'Chinchao', 'Churubamba', 'Huánuco', 'Margos', 'Pillco Marca', 'Quisqui (Kichki)', 'San Francisco de Cayrán', 'San Pablo de Pillao', 'Santa María del Valle', 'Yarumayo'),
        'Lauricocha' => array('Baños', 'Jesús', 'Jivia', 'Queropalca', 'Rondos', 'San Francisco de Asís', 'San Miguel de Cauri'),
        'Leoncio Prado' => array('Castillo Grande', 'Daniel Alomía Robles', 'Hermilio Valdizán', 'José Crespo y Castillo', 'Luyando', 'Mariano Dámaso Beraún', 'Pucayacu', 'Rupa-Rupa (Tingo María)'),
        'Marañón' => array('Cholon', 'Huacrachuco', 'San Buenaventura'),
        'Pachitea' => array('Chaglla', 'Molino', 'Panao', 'Umari'),
        'Puerto Inca' => array('Codo del Pozuzo', 'Honoria', 'Puerto Inca', 'Tournavista', 'Yuyapichis'),
        'Yarowilca' => array('Aparicio Pomares', 'Cahuac', 'Chacabamba', 'Chavinillo', 'Choras', 'Jacas Chico', 'Obas', 'Pampamarca'),
        //Ica
        'Chincha' => array('Alto Larán', 'Chavín', 'Chincha Alta', 'Chincha Baja', 'El Carmen', 'Grocio Prado', 'Pueblo Nuevo', 'San Juan de Yanac', 'San Pedro de Huacarpana', 'Sunampe', 'Tambo de Mora'),
        'Ica' => array('Ica', 'La Tinguiña', 'Los Aquijes', 'Ocucaje', 'Pachacútec', 'Parcona', 'Pueblo Nuevo', 'Salas', 'San José de los Molinos', 'San Juan Bautista', 'Santiago', 'Subtanjalla', 'Tate', 'Yauca del Rosario'),
        'Nazca' => array('Changuillo', 'El Ingenio', 'Marcona', 'Nazca', 'Vista Alegre'),
        'Palpa' => array('Llipata', 'Palpa', 'Río Grande', 'Santa Cruz', 'Tibillo'),
        'Pisco' => array('Huancano', 'Humay', 'Independencia', 'Paracas', 'Pisco', 'San Andrés', 'San Clemente', 'Tupac Amaru Inca'),
        //Junín
        'Chanchamayo' => array('Chanchamayo', 'Perené', 'Pichanaqui', 'San Luis de Shuaro', 'San Ramón', 'Vitoc'),
        'Chupaca' => array('Áhuac', 'Chongos Bajo', 'Chupaca', 'Huáchac', 'Huamancaca Chico', 'San Juan de Iscos', 'San Juan de Jarpa', 'Tres de Diciembre', 'Yanacancha'),
        'Concepción' => array('Aco', 'Andamarca', 'Chambara', 'Cochas', 'Concepción', 'Heroinas Toledo', 'Manzanares', 'Mariscal Castilla', 'Matahuasi', 'Mito', 'Nueve de Julio', 'Orcotuna', 'San José de Quero', 'Santa Rosa de Ocopa'),
        'Huancayo' => array('Carhuacallanga', 'Chacapampa', 'Chicche', 'Chilca', 'Chongos Alto', 'Chupuro', 'Colca', 'Cullhuas', 'El Tambo', 'Huacrapuquio', 'Hualhuas', 'Huancán', 'Huancayo', 'Huasicancha', 'Huayucachi', 'Ingenio', 'Pariahuanca', 'Pilcomayo', 'Pucará', 'Quichuay', 'Quilcas', 'San Agustín', 'San Jerónimo de Tunán', 'Santo Domingo de Acobamba', 'Sapallanga', 'Sicaya', 'Viques'),
        'Jauja' => array('Acolla', 'Apata', 'Ataura', 'Canchayllo', 'Curicaca', 'El Mantaro', 'Huamali', 'Huaripampa', 'Huertas', 'Janjaillo', 'Jauja', 'Julcán', 'Leonor Ordóñez', 'Llocllapampa', 'Marco', 'Masma', 'Masma Chicche', 'Molinos', 'Monobamba', 'Muqui', 'Muquiyauyo', 'Paca', 'Paccha', 'Pancán', 'Parco', 'Pomacancha', 'Ricrán', 'San Lorenzo', 'San Pedro de Chunan', 'Sausa', 'Sincos', 'Tunanmarca', 'Yauli', 'Yauyos'),
        'Junín' => array('Carhuamayo', 'Junín', 'Ondores', 'Ulcumayo'),
        'Satipo' => array('Coviriali', 'Llaylla', 'Mazamari', 'Pampa Hermosa', 'Pangoa', 'Río Negro', 'Río Tambo', 'Satipo'),
        'Tarma' => array('Acobamba', 'Huaricolca', 'Huasahuasi', 'La Unión', 'Palca', 'Palcamayo', 'San Pedro de Cajas', 'Tarma', 'Tapo'),
        'Yauli' => array('Chacapalpa', 'Huayhuay', 'La Oroya', 'Marcapomacocha', 'Morococha', 'Paccha', 'Santa Bárbara de Carhuacayán', 'Santa Rosa de Sacco', 'Suitucancha', 'Yauli'),
        //La Libertad
        'Ascope' => array('Ascope', 'Casa Grande', 'Chicama', 'Chocope', 'Magdalena de Cao', 'Paiján', 'Rázuri', 'Santiago de Cao'),
        'Bolívar' => array('Bolívar', 'Bambamarca', 'Condormarca', 'Longotea', 'Uchumarca', 'Ucuncha'),
        'Chepén' => array('Chepén', 'Pacanga', 'Pueblo Nuevo'),
        'Gran Chimú' => array('Cascas', 'Lucma', 'Marmot', 'Sayapullo'),
        'Julcán' => array('Calamarca', 'Carabamba', 'Huaso', 'Julcán'),
        'Otuzco' => array('Agallpampa', 'Charat', 'Huaranchal', 'La Cuesta', 'Mache', 'Otuzco', 'Paranday', 'Salpo', 'Sinsicap', 'Usquil'),
        'Pacasmayo' => array('Guadalupe', 'Jequetepeque', 'Pacasmayo', 'San José', 'San Pedro de Lloc'),
        'Pataz' => array('Buldibuyo', 'Chillia', 'Huancaspata', 'Huayo', 'Ongón', 'Parcoy', 'Pataz', 'Pías', 'Taurija', 'Tayabamba', 'Urpay'),
        'Sánchez Carrión' => array('Chugay', 'Cochorco', 'Curgos', 'Huamachuco', 'Marcabal', 'Sanagorán', 'Sarin', 'Sartimbamba'),
        'Santiago de Chuco' => array('Angasmarca', 'Cachicadán', 'Mollepata', 'Mollebamba', 'Quiruvilca', 'Santa Cruz de Chuca', 'Santiago de Chuco'),
        'Trujillo' => array('El Porvenir', 'Florencia de Mora', 'Huanchaco', 'La Esperanza', 'Laredo', 'Moche', 'Poroto', 'Salaverry', 'Simbal', 'Trujillo', 'Víctor Larco Herrera'),
        'Virú' => array('Chao', 'Guadalupito', 'Virú'),
        //Lambayeque
        'Chiclayo' => array('Chiclayo', 'Chongoyape', 'Eten', 'Eten Puerto', 'José Leonardo Ortiz', 'La Victoria', 'Lagunas', 'Monsefú', 'Nueva Arica', 'Oyotún', 'Patapo', 'Picsi', 'Pimentel', 'Puerto Etén', 'Pomalca', 'Reque', 'Santa Rosa', 'Saña', 'Tumán'),
        'Ferreñafe' => array('Cañaris', 'Ferreñafe', 'Incahuasi', 'Manuel Antonio Mesones Muro', 'Pitipo', 'Pueblo Nuevo'),
        'Lambayeque' => array('Chóchope', 'Illimo', 'Jayanca', 'Lambayeque', 'Mochumi', 'Morrope', 'Motupe', 'Olmos', 'Pacora', 'Salas', 'San José', 'Túcume'),
        //Lima
        'Barranca' => array('Barranca', 'Paramonga', 'Pativilca', 'Supe', 'Supe Puerto'),
        'Cajatambo' => array('Cajatambo', 'Copa', 'Gorgor', 'Huancapón', 'Manás'),
        'Canta' => array('Arahuay', 'Canta', 'Huamantanga', 'Huaros', 'Lachaqui', 'San Buenaventura', 'Santa Rosa de Quives'),
        'Cañete' => array('Asia', 'Calango', 'Cerro Azul', 'Chilca', 'Coayllo', 'Imperial', 'Lunahuaná', 'Mala', 'Nuevo Imperial', 'Pacarán', 'Quilmana', 'San Antonio', 'San Luis', 'Santa Cruz de Flores', 'Zúñiga'),
        'Huaral' => array('Atavillos Alto', 'Atavillos Bajo', 'Aucallama', 'Chancay', 'Huaral', 'Ihuarí', 'Lampian', 'Pacaraos', 'San Miguel de Acos', 'Santa Cruz de Andamarca', 'Sumbilca', 'Veintisiete de Noviembre'),
        'Huarochirí' => array('Antioquía', 'Callahuanca', 'Carampoma', 'Chicla', 'Cuenca', 'Huachupampa', 'Huanza', 'Huarochirí', 'Lahuaytambo', 'Langa', 'Laraos', 'Mariatana', 'Matucana', 'Ricardo Palma', 'San Andrés de Tupicocha', 'San Antonio', 'San Bartolomé', 'San Damián', 'San Juan de Iris', 'San Juan de Tantaranche', 'San Lorenzo de Quinti', 'San Mateo', 'San Mateo de Otao', 'San Pedro de Casta', 'San Pedro de Huancayre', 'Sangallaya', 'Santa Cruz de Cocachacra', 'Santa Eulalia', 'Santiago de Anchucaya', 'Santiago de Tuna', 'Santo Domingo de Los Olleros', 'San Jerónimo de Surco'),
        'Huaura' => array('Ámbar', 'Caleta de Carquín', 'Checras', 'Hualmay', 'Huaura', 'Leoncio Prado', 'Paccho', 'Santa Leonor', 'Santa María', 'Sayán', 'Vegueta'),
        'Oyón' => array('Andajes', 'Caujul', 'Cochamarca', 'Naván', 'Oyón', 'Pachangara'),
        'Yauyos' => array('Alis', 'Allauca', 'Ayaviri', 'Azángaro', 'Cacra', 'Carania', 'Catahuasi', 'Chocos', 'Cochas', 'Colonia', 'Hongos', 'Huampará', 'Huancaya', 'Huangáscar', 'Huantán', 'Huañec', 'Laraos', 'Lincha', 'Madean', 'Miraflores', 'Omas', 'Putinza', 'Quinches', 'Quinocay', 'San Joaquín', 'San Pedro de Pilas', 'Tanta', 'Tauripampa', 'Tomas', 'Tupe', 'Viñac', 'Vitis'),
        //Loreto
        'Alto Amazonas' => array('Balsapuerto', 'Jeberos', 'Lagunas', 'Santa Cruz', 'Teniente César López Rojas', 'Yurimaguas'),
        'Datem del Marañón' => array('Barranca', 'Cahuapanas', 'Manseriche', 'Morona', 'Pastaza', 'Andoas'),
        'Loreto' => array('Nauta', 'Parinari', 'Tigre', 'Trompeteros', 'Urarinas'),
        'Mariscal Ramón Castilla' => array('Pebas', 'Ramón Castilla', 'San Pablo', 'Yavari'),
        'Maynas' => array('Alto Nanay', 'Fernando Lores', 'Indiana', 'Iquitos', 'Las Amazonas', 'Mazán', 'Napo', 'Punchana', 'Torres Causana'),
        'Putumayo' => array('Putumayo', 'Rosa Panduro', 'Teniente Manuel Clavero', 'Yaguas'),
        'Requena' => array('Cabo Pantoja', 'Flor de Punga', 'Jenaro Herrera', 'Maquía', 'Puínahua', 'Requena', 'Saquena', 'Soplin', 'Tapiche', 'Yaquerana'),
        'Ucayali' => array('Contamana', 'Inahuaya', 'Padre Márquez', 'Pampa Hermosa', 'Sarayacu', 'Vargas Guerra'),
        //Madre de Dios
        'Manu' => array('Fitzcarrald', 'Madre de Dios', 'Manu'),
        'Tahuamanu' => array('Iñapari', 'Iberia', 'Tahuamanu'),
        'Tambopata' => array('Inambari', 'Las Piedras', 'Laberinto', 'Tambopata'),
        //Moquegua
        'General Sánchez Cerro' => array('Chojata', 'Coalaque', 'Ichuña', 'La Capilla', 'Lloque', 'Matalaque', 'Omate', 'Puquina', 'Quinistaquillas', 'Ubinas', 'Yunga'),
        'Ilo' => array('El Algarrobal', 'Ilo', 'Pacocha'),
        'Mariscal Nieto' => array('Carumas', 'Cuchumbaya', 'Moquegua', 'Samegua', 'San Cristóbal', 'Torata'),
        //Pasco
        'Daniel Alcides Carrión' => array('Chacayan', 'Goyllarisquizga', 'Paucar', 'San Pedro de Pillao', 'Santa Ana de Tusi', 'Tapuc', 'Vilcabamba', 'Yanahuanca'),
        'Oxapampa' => array('Chontabamba', 'Constitución', 'Huancabamba', 'Oxapampa', 'Palcazú', 'Pozuzo', 'Puerto Bermúdez', 'Villa Rica'),
        'Pasco' => array('Chaupimarca', 'Huachón', 'Huariaca', 'Huayllay', 'Ninacaca', 'Pallanchacra', 'Paucartambo', 'San Francisco de Asís de Yarusyacán', 'Simón Bolívar', 'Ticlacayán', 'Tinyahuarco', 'Vicco', 'Yanacancha'),
        //Piura
        'Azángaro' => array('Achaya', 'Arapa', 'Asillo', 'Azángaro', 'Caminaca', 'Chupa', 'José Domingo Choquehuanca', 'Muñani', 'Potoni', 'Samán', 'San Antón', 'San José', 'San Juan de Salinas', 'Santiago de Pupuja', 'Tirapata'),
        'Carabaya' => array('Ajoyani', 'Ayapata', 'Coasa', 'Corani', 'Crucero', 'Ituata', 'Macusani', 'Ollachea', 'San Gabán', 'Usicayos'),
        'Chucuito' => array('Desaguadero', 'Huacullani', 'Juli', 'Kelluyo', 'Pisacoma', 'Pomata', 'Zepita'),
        'El Collao' => array('Capazo', 'Conduriri', 'Ilave', 'Pilcuyo', 'Santa Rosa'),
        'Huancané' => array('Cojata', 'Huancané', 'Huatasani', 'Inchupalla', 'Pusi', 'Rosaspata', 'Taraco', 'Vilque Chico'),
        'Lampa' => array('Cabanilla', 'Calapuja', 'Lampa', 'Nicasio', 'Ocuviri', 'Palca', 'Paratía', 'Pucará', 'Santa Lucía', 'Vilavila'),
        'Melgar' => array('Antauta', 'Ayaviri', 'Cupi', 'Llalli', 'Macari', 'Nuñoa', 'Orurillo', 'Santa Rosa', 'Umachiri'),
        'Moho' => array('Conima', 'Huayrapata', 'Moho', 'Tilali'),
        'Puno' => array('Acora', 'Amantani', 'Atuncolla', 'Capachica', 'Chucuito', 'Coata', 'Huata', 'Mañazo', 'Paucarcolla', 'Pichacani', 'Platería', 'Puno', 'San Antonio', 'Tiquillaca', 'Vilque'),
        'San Antonio de Putina' => array('Ananea', 'Pedro Vilca Apaza', 'Putina', 'Quilcapuncu', 'Sina'),
        'San Román' => array('Cabana', 'Cabanillas', 'Caracoto', 'Juliaca'),
        'Sandia' => array('Alto Inambari', 'Cuyocuyo', 'Limbani', 'Patambuco', 'Phara', 'Quiaca', 'San Juan del Oro', 'San Pedro de Putina Punco', 'Sandia', 'Yanahuaya'),
        'Yunguyo' => array('Anapia', 'Copani', 'Cuturapi', 'Ollaraya', 'Tinicachi', 'Unicachi', 'Yunguyo'),
        //Puno
        'Azángaro' => array('Achaya', 'Arapa', 'Asillo', 'Azángaro', 'Caminaca', 'Chupa', 'José Domingo Choquehuanca', 'Muñani', 'Potoni', 'Samán', 'San Antón', 'San José', 'San Juan de Salinas', 'Santiago de Pupuja', 'Tirapata'),
        'Carabaya' => array('Ajoyani', 'Ayapata', 'Coasa', 'Corani', 'Crucero', 'Ituata', 'Macusani', 'Ollachea', 'San Gabán', 'Usicayos'),
        'Chucuito' => array('Desaguadero', 'Huacullani', 'Juli', 'Kelluyo', 'Pisacoma', 'Pomata', 'Zepita'),
        'El Collao' => array('Capazo', 'Conduriri', 'Ilave', 'Pilcuyo', 'Santa Rosa'),
        'Huancané' => array('Cojata', 'Huancané', 'Huatasani', 'Inchupalla', 'Pusi', 'Rosaspata', 'Taraco', 'Vilque Chico'),
        'Lampa' => array('Cabanilla', 'Calapuja', 'Lampa', 'Nicasio', 'Ocuviri', 'Palca', 'Paratía', 'Pucará', 'Santa Lucía', 'Vilavila'),
        'Melgar' => array('Antauta', 'Ayaviri', 'Cupi', 'Llalli', 'Macari', 'Nuñoa', 'Orurillo', 'Santa Rosa', 'Umachiri'),
        'Moho' => array('Conima', 'Huayrapata', 'Moho', 'Tilali'),
        'Puno' => array('Acora', 'Amantani', 'Atuncolla', 'Capachica', 'Chucuito', 'Coata', 'Huata', 'Mañazo', 'Paucarcolla', 'Pichacani', 'Platería', 'Puno', 'San Antonio', 'Tiquillaca', 'Vilque'),
        'San Antonio de Putina' => array('Ananea', 'Pedro Vilca Apaza', 'Putina', 'Quilcapuncu', 'Sina'),
        'San Román' => array('Cabana', 'Cabanillas', 'Caracoto', 'Juliaca'),
        'Sandia' => array('Alto Inambari', 'Cuyocuyo', 'Limbani', 'Patambuco', 'Phara', 'Quiaca', 'San Juan del Oro', 'San Pedro de Putina Punco', 'Sandia', 'Yanahuaya'),
        'Yunguyo' => array('Anapia', 'Copani', 'Cuturapi', 'Ollaraya', 'Tinicachi', 'Unicachi', 'Yunguyo'),
        //San Martín
        'Bellavista' => array('Alto Biavo', 'Bajo Biavo', 'Bellavista', 'Huallaga', 'San Pablo', 'San Rafael'),
        'El Dorado' => array('Agua Blanca', 'San José de Sisa', 'San Martín', 'Santa Rosa', 'Shatoja'),
        'Huallaga' => array('Alto Saposoa', 'El Eslabón', 'Piscoyacu', 'Sacanche', 'Saposoa', 'Tingo de Saposoa'),
        'Lamas' => array('Alonso de Alvarado', 'Barranquita', 'Caynarachi', 'Cuñumbuqui', 'Lamas', 'Pinto Recodo', 'Rumisapa', 'San Roque de Cumbaza', 'Shanao', 'Tabalosos', 'Zapatero'),
        'Mariscal Cáceres' => array('Campanilla', 'Huicungo', 'Juanjuí', 'Pachiza', 'Pajarillo'),
        'Moyobamba' => array('Calzada', 'Habana', 'Jepelacio', 'Moyobamba', 'Soritor', 'Yantalo'),
        'Picota' => array('Buenos Aires', 'Caspisapa', 'Picota', 'Pilluana', 'Pucacaca', 'San Cristóbal', 'San Hilarión', 'Shamboyacu', 'Tingo de Ponasa', 'Tres Unidos'),
        'Rioja' => array('Awajun', 'Elias Soplín Vargas', 'Nueva Cajamarca', 'Pardo Miguel', 'Posic', 'Rioja', 'San Fernando', 'Yorongos', 'Yuracyacu'),
        'San Martín' => array('Alberto Leveau', 'Cacatachi', 'Chazuta', 'Chipurana', 'El Porvenir', 'Huimbayoc', 'Juan Guerra', 'La Banda de Shilcayo', 'Morales', 'Papaplaya', 'San Antonio', 'Sauce', 'Shapaja', 'Tarapoto'),
        'Tocache' => array('Nuevo Progreso', 'Polvora', 'Shunte', 'Tocache', 'Uchiza'),
        //Tacna
        'Candarave' => array('Cairani', 'Camilaca', 'Candarave', 'Curibaya', 'Huanuara', 'Quilahuani'),
        'Jorge Basadre' => array('Ilabaya', 'Ite', 'Locumba'),
        'Tacna' => array('Alto de la Alianza', 'Calana', 'Ciudad Nueva', 'Coronel Gregorio Albarracín Lanchipa', 'Inclán', 'Pachía', 'Palca', 'Pocollay', 'Sama', 'Tacna'),
        'Tarata' => array('Chucatamani', 'Estique', 'Estique-Pampa', 'Heroes Albarracín', 'Sitajara', 'Susapaya', 'Tarata', 'Ticaco'),
        //Tumbes
        'Contralmirante Villar' => array('Casitas', 'Zorritos'),
        'Tumbes' => array('Corrales', 'La Cruz', 'Pampas de Hospital', 'San Jacinto', 'San Juan de la Virgen', 'Tumbes'),
        'Zarumilla' => array('Aguas Verdes', 'Matapalo', 'Papayal', 'Zarumilla'),
        //Ucayali
        'Atalaya' => array('Raymondi', 'Sepahua', 'Tahuania', 'Yurua'),
        'Coronel Portillo' => array('Callería', 'Campoverde', 'Iparía', 'Masisea', 'Nueva Requena', 'Yarinacocha'),
        'Padre Abad' => array('Curimaná', 'Irázola', 'Padre Abad'),
        'Purús' => array('Purús'),
    );

    return isset($distritos[$provincia]) ? $distritos[$provincia] : array();
}